"""
Antigravity-Alpha Database Models
SQLAlchemy ORM models for storing coin data, OHLCV, and analysis results
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, Boolean, Enum
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import enum

Base = declarative_base()


class TimeFrame(enum.Enum):
    """Supported timeframes for analysis"""
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"


class TradeDirection(enum.Enum):
    """Trade direction"""
    LONG = "LONG"
    SHORT = "SHORT"


class Coin(Base):
    """Coin basic information"""
    __tablename__ = "coins"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), unique=True, nullable=False, index=True)  # e.g., "BTCUSDT"
    name = Column(String(100))  # e.g., "Bitcoin"
    market_cap_rank = Column(Integer)  # 1-200
    coingecko_id = Column(String(100))  # For CoinGecko API
    binance_symbol = Column(String(20))  # Binance trading pair
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    ohlcv_data = relationship("OHLCV", back_populates="coin", cascade="all, delete-orphan")
    market_data = relationship("MarketData", back_populates="coin", cascade="all, delete-orphan")
    analysis_results = relationship("AnalysisResult", back_populates="coin", cascade="all, delete-orphan")


class OHLCV(Base):
    """Price OHLCV data"""
    __tablename__ = "ohlcv"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(Integer, ForeignKey("coins.id"), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False)  # "1h", "4h", "1d", "1w"
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    
    # Relationship
    coin = relationship("Coin", back_populates="ohlcv_data")


class MarketData(Base):
    """Market indicators (OI, Funding Rate, CVD)"""
    __tablename__ = "market_data"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(Integer, ForeignKey("coins.id"), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    
    # Market Indicators
    open_interest = Column(Float)  # Open Interest
    funding_rate = Column(Float)   # Funding Rate
    cvd = Column(Float)            # Cumulative Volume Delta
    
    # On-chain like indicators (from free APIs)
    whale_transaction_count = Column(Integer)  # Large transaction count
    exchange_inflow = Column(Float)            # Exchange inflow volume
    exchange_outflow = Column(Float)           # Exchange outflow volume
    
    # Relationship
    coin = relationship("Coin", back_populates="market_data")


class AnalysisResult(Base):
    """Analysis results from pattern detection and scoring"""
    __tablename__ = "analysis_results"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(Integer, ForeignKey("coins.id"), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Pattern Detection Results
    has_mss = Column(Boolean, default=False)          # Market Structure Shift
    has_fvg = Column(Boolean, default=False)          # Fair Value Gap
    has_spring = Column(Boolean, default=False)       # Wyckoff Spring
    has_vcp = Column(Boolean, default=False)          # Volatility Contraction Pattern
    wyckoff_phase = Column(String(50))                # Current Wyckoff Phase
    
    # Confluence & Scores
    ict_score = Column(Float, default=0)
    wyckoff_score = Column(Float, default=0)
    vcp_score = Column(Float, default=0)
    onchain_score = Column(Float, default=0)
    total_score = Column(Float, default=0)
    
    # Trade Setup
    direction = Column(String(10))  # "LONG" or "SHORT"
    conviction = Column(String(20))  # "HIGH", "MEDIUM", "LOW"
    
    # Relationship
    coin = relationship("Coin", back_populates="analysis_results")
    trade_plan = relationship("TradePlan", back_populates="analysis", uselist=False, cascade="all, delete-orphan")


class TradePlan(Base):
    """Trade plan generated by CIO Agent"""
    __tablename__ = "trade_plans"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    analysis_id = Column(Integer, ForeignKey("analysis_results.id"), nullable=False, unique=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    # Entry & Risk Management
    current_price = Column(Float)
    entry_price = Column(Float)
    entry_zone_low = Column(Float)
    entry_zone_high = Column(Float)
    stop_loss = Column(Float)
    
    # Targets
    target_1 = Column(Float)  # R:R 1:1
    target_2 = Column(Float)  # R:R 1:2
    target_3 = Column(Float)  # R:R 1:3+
    
    # Reasoning
    key_reasons = Column(Text)  # JSON list of key reasons
    risk_factors = Column(Text)  # JSON list of risk factors
    agent_reasoning = Column(Text)  # Full LLM reasoning
    
    # Status
    is_reported = Column(Boolean, default=False)
    reported_at = Column(DateTime)
    
    # Relationship
    analysis = relationship("AnalysisResult", back_populates="trade_plan")


# Database initialization helper
def init_database(database_url: str = "sqlite:///./data/antigravity.db"):
    """Initialize database and create all tables"""
    engine = create_engine(database_url, echo=False)
    Base.metadata.create_all(engine)
    return engine


def get_session(engine):
    """Get database session"""
    Session = sessionmaker(bind=engine)
    return Session()
